targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  clusterName: budget-gamer-cluster
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: false